apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: bobbins/frontend:0.2
        env:
          - name: Services__Links__BaseUrl
            value: "http://links"
          - name: Services__Comments__BaseUrl
            value: "http://comments"
          - name: DataProtection__Redis
            value: "redis"
          - name: ConnectionStrings__DefaultConnection
            valueFrom:
              secretKeyRef:
                name: frontend-db
                key: connstr
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    name: http
  selector:
    app: frontend