apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: links
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: links
    spec:
      containers:
      - name: links
        image: bobbins/links:0.1
        env:
          - name: ConnectionStrings__Links
            valueFrom:
              secretKeyRef:
                name: links-db
                key: connstr
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: links
  labels:
    app: links
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: links