apiVersion: batch/v1
kind: Job
metadata:
  name: links-migrate
spec:
  template:
    metadata:
      name: links-migrate
    spec:
      containers:
      - name: links-migrate
        image: bobbins/links-migrate:0.1
        args: ["$(SECRET_CONNSTR)"]
        env:
          - name: SECRET_CONNSTR
            valueFrom:
              secretKeyRef:
                name: links-db
                key: connstr
      restartPolicy: OnFailure